name: Create Release Branch
on:
  workflow_dispatch:
    ref: develop
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
jobs:
  call-ci:
    uses: baarsa/opera-guide-typegraphql/.github/workflows/services-ci.yml@master
  createrelease:
    needs: call-ci
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create release branch
        run: git checkout -b release/v${{ github.event.inputs.versionName }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Change version number for front package
        working-directory: ./mss-front
        run: npm version ${{ github.event.inputs.versionName }}
      - name: Change version number for api package
        working-directory: ./mss-api
        run: npm version ${{ github.event.inputs.versionName }}
      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ github.event.inputs.versionName }}
      - name: Commit updated files
        id: make-commit
        run: |
          git add ./mss-front/package.json
          git add ./mss-front/package-lock.json
          git add ./mss-api/package.json
          git add ./mss-api/package-lock.json
          git add CHANGELOG.md
          git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin release/v${{ github.event.inputs.versionName }}
      - name: Create pull request into master
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/v${{ github.event.inputs.versionName }}
          base: master
          title: v${{ github.event.inputs.versionName }} into master
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
      - name: Create pull request into develop
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/v${{ github.event.inputs.versionName }}
          base: develop
          title: v${{ github.event.inputs.versionName }} into develop
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.