name: Services CI
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
      - develop
  workflow_call:
jobs:
  ci-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mss-front
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NODE_ENV: 'production'
      - name: Test
        run: npm test
      - name: Lint
        run: npm run lint
  ci-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mss-api
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NODE_ENV: 'production'
      - name: Test
        run: npm test
